- name: download OpenVSwitch sources
  get_url: url=http://openvswitch.org/releases/openvswitch-2.3.2.tar.gz dest=/root/rpmbuild/SOURCES/openvswitch-2.3.2.tar.gz

- name: unpack OpenVSwitch sources
  unarchive: src=/root/rpmbuild/SOURCES/openvswitch-2.3.2.tar.gz dest=/root/ copy=no

- name: install prereqs
  yum: name={{ item }} state=present
  with_items:
    - rpm-build
    - openssl-devel
    - autoconf
    - graphviz
    - python-twisted-core
    - PyQt4
    - groff

- name: build the RPM
  shell: cd /root/openvswitch-2.3.2 && rpmbuild -bb rhel/openvswitch.spec creates=/root/rpmbuild/RPMS/x86_64/openvswitch-2.3.2-1.x86_64.rpm
  when: ansible_distribution_major_version == '6'

- name: build the RPM
  shell: cd /root/openvswitch-2.3.2 && rpmbuild -bb rhel/openvswitch-fedora.spec creates=/root/rpmbuild/RPMS/x86_64/openvswitch-2.3.2-1.el7.centos.x86_64.rpm
  when: ansible_distribution_major_version == '7'

- name: install OpenVSwitch RPM
  yum: name=/root/rpmbuild/RPMS/x86_64/openvswitch-2.3.2-1.el7.centos.x86_64.rpm state=present
